import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/**/*.{ts,tsx,html}",
    "./.storybook/**/*.{ts,tsx,html}",
  ],
  theme: {
    extend: {
      colors: {
        "ds-bg": "var(--ds-bg)",
        "ds-fg": "var(--ds-fg)",
        "ds-muted": "var(--ds-muted)",
        "ds-border": "var(--ds-border)",
        "ds-ring": "var(--ds-ring)",
        "ds-primary": "var(--ds-primary)",
        "ds-primary-fg": "var(--ds-primary-fg)",
        "ds-secondary": "var(--ds-secondary)",
        "ds-secondary-fg": "var(--ds-secondary-fg)",
        "ds-success": "var(--ds-success)",
        "ds-success-fg": "var(--ds-success-fg)",
        "ds-warning": "var(--ds-warning)",
        "ds-warning-fg": "var(--ds-warning-fg)",
        "ds-info": "var(--ds-info)",
        "ds-info-fg": "var(--ds-info-fg)",
        "ds-error": "var(--ds-error)",
        "ds-error-fg": "var(--ds-error-fg)",
      },
      spacing: {
        xs: "var(--ds-spacing-xs)",
        sm: "var(--ds-spacing-sm)",
        md: "var(--ds-spacing-md)",
        lg: "var(--ds-spacing-lg)",
        xl: "var(--ds-spacing-xl)",
        "2xl": "var(--ds-spacing-2xl)",
        "3xl": "var(--ds-spacing-3xl)",
        "4xl": "var(--ds-spacing-4xl)",
        "5xl": "var(--ds-spacing-5xl)",
      },
      fontSize: {
        "ds-xs": "var(--ds-font-size-xs)",
        "ds-sm": "var(--ds-font-size-sm)",
        "ds-md": "var(--ds-font-size-md)",
        "ds-lg": "var(--ds-font-size-lg)",
        "ds-xl": "var(--ds-font-size-xl)",
        "ds-2xl": "var(--ds-font-size-2xl)",
        "ds-3xl": "var(--ds-font-size-3xl)",
        "ds-4xl": "var(--ds-font-size-4xl)",
        "ds-5xl": "var(--ds-font-size-5xl)",
      },
      fontWeight: {
        "ds-light": "var(--ds-font-weight-light)",
        "ds-normal": "var(--ds-font-weight-normal)",
        "ds-medium": "var(--ds-font-weight-medium)",
        "ds-semibold": "var(--ds-font-weight-semibold)",
        "ds-bold": "var(--ds-font-weight-bold)",
        "ds-extrabold": "var(--ds-font-weight-extrabold)",
        "ds-black": "var(--ds-font-weight-black)",
      },
      borderRadius: {
        sm: "var(--ds-radius-sm)",
        md: "var(--ds-radius-md)",
        lg: "var(--ds-radius-lg)",
      },
      transitionDuration: {
        "ds-2s": "var(--ds-transition-2s)",
        "ds-3s": "var(--ds-transition-3s)",
        "ds-4s": "var(--ds-transition-4s)",
        "ds-5s": "var(--ds-transition-5s)",
        "ds-6s": "var(--ds-transition-6s)",
        "ds-7s": "var(--ds-transition-7s)",
        "ds-8s": "var(--ds-transition-8s)",
        "ds-9s": "var(--ds-transition-9s)",
        "ds-10s": "var(--ds-transition-10s)",
      },
      boxShadow: {
        "ds-sm": "var(--ds-shadow-sm)",
        "ds-md": "var(--ds-shadow-md)",
        "ds-lg": "var(--ds-shadow-lg)",
        "ds-xl": "var(--ds-shadow-xl)",
        "ds-2xl": "var(--ds-shadow-2xl)",
        "ds-inner": "var(--ds-shadow-inner)",
        "ds-none": "var(--ds-shadow-none)",
      },
    },
  },
  plugins: [],
} satisfies Config;
